/* Generated by Together */

/**
 * @persistent
 * @rdbPhysicalName APARTAMENTO
 * @rdbPhysicalPrimaryKeyName APARTAMENTO_ID_PK 
 */
public class APARTAMENTO {
    public APARTAMENTO() {
    }

    /**
     * @rdbPhysicalName PREDIO
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR
     * @rdbPrimaryKey 
     */
    private String PREDIO;

    /**
     * @rdbPhysicalName APTO
     * @rdbNotNull
     * @rdbSize 3
     * @rdbLogicalType TINYINT
     * @rdbPrimaryKey 
     */
    private byte APTO;

    /**
     * @rdbPhysicalName RAMAL
     * @rdbSize 4
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String RAMAL;

    /**
     * @rdbPhysicalName TV1
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String TV1;

    /**
     * @rdbPhysicalName TV2
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String TV2;

    /**
     * @rdbPhysicalName PREDIO1
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String PREDIO1;

    /**
     * @rdbPhysicalName APTO1
     * @rdbNotNull
     * @rdbSize 3
     * @rdbLogicalType TINYINT 
     */
    private byte APTO1;

    /**
     * @rdbPhysicalName RAMAL1
     * @rdbSize 4
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String RAMAL1;

    /**
     * @rdbPhysicalName TV3
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String TV3;

    /**
     * @rdbPhysicalName TV4
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String TV4;
}
