/* Generated by Together */

/**
 * @persistent
 * @rdbPhysicalName <{APTOCAMA}>
 * @rdbPhysicalPrimaryKeyName APTOCAMA_ID_PK 
 */
public class APTOCAMA {
    public APTOCAMA() {
    }

    /**
     * @rdbPhysicalName PREDIO
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR
     * @rdbPrimaryKey 
     */
    private String PREDIO;

    /**
     * @rdbPhysicalName APTO
     * @rdbNotNull
     * @rdbSize 3
     * @rdbLogicalType TINYINT
     * @rdbPrimaryKey 
     */
    private byte APTO;

    /**
     * @rdbPhysicalName CAMA
     * @rdbNotNull
     * @rdbSize 2
     * @rdbLogicalType TINYINT
     * @rdbPrimaryKey 
     */
    private byte CAMA;

    /**
     * @rdbPhysicalName APTCODIGO
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String APTCODIGO;

    /**
     * @rdbPhysicalName NOME
     * @rdbSize 30
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String NOME;
}
