/* Generated by Together */

/**
 * @persistent
 * @rdbPhysicalName FACILIDADE 
 */
public class FACILIDADE {
    public FACILIDADE() {
    }

    /**
     * @rdbPhysicalName TIPO
     * @rdbSize 20
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String TIPO;

    /**
     * @rdbPhysicalName NOME
     * @rdbSize 35
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String NOME;

    /**
     * @rdbPhysicalName TELEFONE
     * @rdbSize 15
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String TELEFONE;

    /**
     * @rdbPhysicalName ENDERECO
     * @rdbSize 35
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String ENDERECO;

    /**
     * @rdbPhysicalName HORARIO
     * @rdbSize 25
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String HORARIO;

    /**
     * @rdbPhysicalName OBS
     * @rdbSize 30
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String OBS;

    /**
     * @rdbPhysicalName TIPO1
     * @rdbSize 20
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String TIPO1;

    /**
     * @rdbPhysicalName NOME1
     * @rdbSize 35
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String NOME1;

    /**
     * @rdbPhysicalName TELEFONE1
     * @rdbSize 15
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String TELEFONE1;

    /**
     * @rdbPhysicalName ENDERECO1
     * @rdbSize 35
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String ENDERECO1;

    /**
     * @rdbPhysicalName HORARIO1
     * @rdbSize 25
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String HORARIO1;

    /**
     * @rdbPhysicalName OBS1
     * @rdbSize 30
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String OBS1;
}
