/* Generated by Together */
import java.sql.Timestamp;

/**
 * @persistent
 * @rdbPhysicalName <{HISTORICO}>
 * @rdbPhysicalPrimaryKeyName HISTORICO_NUMSEQ_PK 
 */
public class HISTORICO {
    public HISTORICO() {
    }

    /**
     * @rdbPhysicalName NUMSEQ
     * @rdbNotNull
     * @rdbSize 5
     * @rdbLogicalType TINYINT
     * @rdbPrimaryKey 
     */
    private byte NUMSEQ;

    /**
     * @rdbPhysicalName IDENTIDADE
     * @rdbSize 18
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     * @rdbPrimaryKey 
     */
    private String IDENTIDADE;

    /**
     * @rdbPhysicalName NOME
     * @rdbSize 40
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String NOME;

    /**
     * @rdbPhysicalName POSTOGRAD
     * @rdbSize 5
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String POSTOGRAD;

    /**
     * @rdbPhysicalName QUADROESPEC
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String QUADROESPEC;

    /**
     * @rdbPhysicalName UNIDADEPER
     * @rdbSize 12
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String UNIDADEPER;

    /**
     * @rdbPhysicalName UNIDADESER
     * @rdbSize 12
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String UNIDADESER;

    /**
     * @rdbPhysicalName CODCURSO
     * @rdbSize 7
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String CODCURSO;

    /**
     * @rdbPhysicalName TURMA
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String TURMA;

    /**
     * @rdbPhysicalName ANO
     * @rdbSize 4
     * @rdbLogicalType TINYINT
     * @rdbPrimaryKey 
     */
    private byte ANO;

    /**
     * @rdbPhysicalName TIPO
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String TIPO;

    /**
     * @rdbPhysicalName PAIS
     * @rdbSize 12
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String PAIS;

    /**
     * @rdbPhysicalName DATAINI
     * @rdbSize 7
     * @rdbDigits 0
     * @rdbLogicalType TIMESTAMP 
     */
    private Timestamp DATAINI;

    /**
     * @rdbPhysicalName DATATER
     * @rdbSize 7
     * @rdbDigits 0
     * @rdbLogicalType TIMESTAMP 
     */
    private Timestamp DATATER;

    /**
     * @rdbPhysicalName SITUACAO
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String SITUACAO;

    /**
     * @rdbPhysicalName NOTA
     * @rdbSize 5
     * @rdbLogicalType TINYINT 
     */
    private byte NOTA;

    /**
     * @rdbPhysicalName FICHA
     * @rdbNotNull
     * @rdbSize 6
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     * @rdbPrimaryKey 
     */
    private String FICHA;

    /**
     * @rdbPhysicalName PREDIO
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String PREDIO;

    /**
     * @rdbPhysicalName APTO
     * @rdbSize 3
     * @rdbLogicalType TINYINT 
     */
    private byte APTO;

    /**
     * @rdbPhysicalName DATAENTRADA
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String DATAENTRADA;

    /**
     * @rdbPhysicalName HORAENTRADA
     * @rdbSize 4
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String HORAENTRADA;

    /**
     * @rdbPhysicalName DATASAIDA
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String DATASAIDA;

    /**
     * @rdbPhysicalName DATAPAGAMENTO
     * @rdbSize 8
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String DATAPAGAMENTO;

    /**
     * @rdbPhysicalName NRECIBO
     * @rdbSize 6
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String NRECIBO;

    /**
     * @rdbPhysicalName BANCO
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String BANCO;

    /**
     * @rdbPhysicalName NCHEQUE
     * @rdbSize 6
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String NCHEQUE;

    /**
     * @rdbPhysicalName PRACA
     * @rdbSize 16
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String PRACA;

    /**
     * @rdbPhysicalName VALORPAGO
     * @rdbSize 8
     * @rdbLogicalType TINYINT 
     */
    private byte VALORPAGO;

    /**
     * @rdbPhysicalName CUSTO_TELEFONE
     * @rdbSize 8
     * @rdbLogicalType TINYINT 
     */
    private byte CUSTO_TELEFONE;

    /**
     * @rdbPhysicalName USUARIO_ENTRADA
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String USUARIO_ENTRADA;

    /**
     * @rdbPhysicalName SITUACAO_CURSO
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String SITUACAO_CURSO;

    /**
     * @rdbPhysicalName USUARIO_SAIDA
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String USUARIO_SAIDA;

    /**
     * @rdbPhysicalName TIPO_FECHAMENTO
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String TIPO_FECHAMENTO;

    /**
     * @rdbPhysicalName RECEBIDO
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String RECEBIDO;

    /**
     * @rdbPhysicalName OBS
     * @rdbSize 150
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String OBS;

    /**
     * @label Refere a
     * @clientCardinality 1 
     */
    private HOSPEDAGEM HOSPEDAGEM;
}
