/* Generated by Together */

public class HOSPEDE {
    /**
     * @rdbPhysicalName IDENTIDADE
     * @rdbNotNull
     * @rdbSize 12
     * @rdbDigits 0
     * @rdbLogicalType CHAR
     * @rdbPrimaryKey 
     */
    private String IDENTIDADE;

    /**
     * @rdbPhysicalName NOME
     * @rdbSize 40
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String NOME;

    /**
     * @rdbPhysicalName NOME_GUERRA
     * @rdbSize 15
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String NOME_GUERRA;

    /**
     * @rdbPhysicalName POSTO
     * @rdbSize 30
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String POSTO;

    /**
     * @rdbPhysicalName NACIONALIDADE
     * @rdbSize 3
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String NACIONALIDADE;

    /**
     * @rdbPhysicalName TELEFONE_RESIDENCIAL
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String TELEFONE_RESIDENCIAL;

    /**
     * @rdbPhysicalName TELEFONE_FUNCIONAL
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String TELEFONE_FUNCIONAL;

    /**
     * @rdbPhysicalName SITUACAO_CURSO
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String SITUACAO_CURSO;

    /**
     * @rdbPhysicalName RESIDENCIA
     * @rdbSize 40
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String RESIDENCIA;

    /**
     * @rdbPhysicalName NUMERO
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String NUMERO;

    /**
     * @rdbPhysicalName CIDADE
     * @rdbSize 40
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String CIDADE;

    /**
     * @rdbPhysicalName BAIRRO
     * @rdbSize 40
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String BAIRRO;

    /**
     * @rdbPhysicalName ESTADO
     * @rdbSize 2
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String ESTADO;

    /**
     * @rdbPhysicalName OM_ORIGEM
     * @rdbSize 20
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String OM_ORIGEM;

    /**
     * @rdbPhysicalName DEPENDENTE_DE
     * @rdbSize 30
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String DEPENDENTE_DE;

    /**
     * @rdbPhysicalName SITUACAO
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String SITUACAO;

    /**
     * @rdbPhysicalName OBS
     * @rdbSize 50
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String OBS;
}
