/* Generated by Together */

/**
 * @persistent
 * @rdbPhysicalName <{HOSPEDAGEM}>
 * @rdbPhysicalPrimaryKeyName HOSPEDAGEM_ID_PK 
 */
public class HOSPEDAGEM {
    public HOSPEDAGEM() {
    }

    /**
     * @rdbPhysicalName IDENTIDADE
     * @rdbNotNull
     * @rdbSize 12
     * @rdbDigits 0
     * @rdbLogicalType CHAR
     * @rdbPrimaryKey 
     */
    private String IDENTIDADE;

    /**
     * @rdbPhysicalName FICHA
     * @rdbNotNull
     * @rdbSize 6
     * @rdbDigits 0
     * @rdbLogicalType CHAR
     * @rdbPrimaryKey 
     */
    private String FICHA;

    /**
     * @rdbPhysicalName ANO
     * @rdbNotNull
     * @rdbSize 4
     * @rdbLogicalType TINYINT
     * @rdbPrimaryKey 
     */
    private byte ANO;

    /**
     * @rdbPhysicalName PREDIO
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String PREDIO;

    /**
     * @rdbPhysicalName APTO
     * @rdbSize 3
     * @rdbLogicalType TINYINT 
     */
    private byte APTO;

    /**
     * @rdbPhysicalName CAMA
     * @rdbSize 2
     * @rdbLogicalType TINYINT 
     */
    private byte CAMA;

    /**
     * @rdbPhysicalName DATAENTRADA
     * @rdbSize 13
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String DATAENTRADA;

    /**
     * @rdbPhysicalName HORAENTRADA
     * @rdbSize 4
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String HORAENTRADA;

    /**
     * @rdbPhysicalName DATASAIDA
     * @rdbSize 13
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String DATASAIDA;

    /**
     * @rdbPhysicalName DEPENDENTE
     * @rdbSize 3
     * @rdbLogicalType TINYINT 
     */
    private byte DEPENDENTE;

    /**
     * @rdbPhysicalName SITUACAO_HOSPEDAGEM
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String SITUACAO_HOSPEDAGEM;

    /**
     * @rdbPhysicalName RECEBE
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String RECEBE;

    /**
     * @rdbPhysicalName DESCONTO
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String DESCONTO;
    private HOSPEDE HOSPEDE;

    /**
     * @label Registra número da ficha no atributo aptcodigo
     * @clientCardinality 1 
     */
    private APTOCAMA lnkAPTOCAMA;
}
