/* Generated by Together */
import java.sql.Timestamp;

/**
 * @persistent
 * @rdbPhysicalName HOTEL_LOGS 
 */
public class HOTEL_LOGS {
    public HOTEL_LOGS() {
    }

    /**
     * @rdbPhysicalName USUARIO
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String USUARIO;

    /**
     * @rdbPhysicalName ATIVIDADE
     * @rdbSize 20
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String ATIVIDADE;

    /**
     * @rdbPhysicalName DATA
     * @rdbSize 7
     * @rdbDigits 0
     * @rdbLogicalType TIMESTAMP 
     */
    private Timestamp DATA;

    /**
     * @rdbPhysicalName HORAENTRADA
     * @rdbSize 5
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String HORAENTRADA;

    /**
     * @rdbPhysicalName NATIVIDADE
     * @rdbSize 5
     * @rdbLogicalType TINYINT 
     */
    private byte NATIVIDADE;

    /**
     * @rdbPhysicalName USUARIO1
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String USUARIO1;

    /**
     * @rdbPhysicalName ATIVIDADE1
     * @rdbSize 20
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String ATIVIDADE1;

    /**
     * @rdbPhysicalName DATA1
     * @rdbSize 7
     * @rdbDigits 0
     * @rdbLogicalType TIMESTAMP 
     */
    private Timestamp DATA1;

    /**
     * @rdbPhysicalName HORAENTRADA1
     * @rdbSize 5
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String HORAENTRADA1;

    /**
     * @rdbPhysicalName NATIVIDADE1
     * @rdbSize 5
     * @rdbLogicalType TINYINT 
     */
    private byte NATIVIDADE1;
}
