/* Generated by Together */

/**
 * @persistent
 * @rdbPhysicalName LOG 
 */
public class LOG {
    public LOG() {
    }

    /**
     * @rdbPhysicalName STATUS
     * @rdbSize 1
     * @rdbLogicalType TINYINT 
     */
    private byte STATUS;
}
