/* Generated by Together */
import java.sql.Timestamp;

/**
 * @persistent
 * @rdbPhysicalName <{ReservaHospedagem}>
 */
public class ReservaHospedagem {
    public ReservaHospedagem() {
    }

    /**
     * @label Transforma-se em
     * @clientCardinality 1..**/
    private HOSPEDAGEM lnkHOSPEDAGEM1;
    private RESERVA Reserva;
}
