/* Generated by Together */
import java.sql.Timestamp;

/**
 * @persistent
 * @rdbPhysicalName <{RESERVA}>
 */
public class RESERVA {
    /**
     * @rdbPhysicalName IDENTIDADE
     * @rdbSize 12
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String IDENTIDADE;

    /**
     * @rdbPhysicalName DATAENTRADA
     * @rdbSize 7
     * @rdbDigits 0
     * @rdbLogicalType TIMESTAMP 
     */
    private Timestamp DATAENTRADA;

    /**
     * @rdbPhysicalName NOME
     * @rdbSize 40
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String NOME;

    /**
     * @rdbPhysicalName NOME_GUERRA
     * @rdbSize 15
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String NOME_GUERRA;

    /**
     * @rdbPhysicalName POSTO
     * @rdbSize 30
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String POSTO;

    /**
     * @rdbPhysicalName DEPENDENTE_DE
     * @rdbSize 30
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String DEPENDENTE_DE;

    /**
     * @rdbPhysicalName TELEFONE_FUNCIONAL
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String TELEFONE_FUNCIONAL;

    /**
     * @rdbPhysicalName SITUACAO_CURSO
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String SITUACAO_CURSO;

    /**
     * @rdbPhysicalName OM_ORIGEM
     * @rdbSize 20
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String OM_ORIGEM;

    /**
     * @rdbPhysicalName DEPENDENTE
     * @rdbSize 3
     * @rdbLogicalType TINYINT 
     */
    private byte DEPENDENTE;

    /**
     * @rdbPhysicalName HORAENTRADA
     * @rdbSize 4
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String HORAENTRADA;

    /**
     * @rdbPhysicalName DATASAIDA
     * @rdbSize 7
     * @rdbDigits 0
     * @rdbLogicalType TIMESTAMP 
     */
    private Timestamp DATASAIDA;

    /**
     * @rdbPhysicalName PREDIO
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String PREDIO;

    /**
     * @rdbPhysicalName APTO
     * @rdbSize 3
     * @rdbLogicalType TINYINT 
     */
    private byte APTO;

    /**
     * @rdbPhysicalName CAMA
     * @rdbSize 2
     * @rdbLogicalType TINYINT 
     */
    private byte CAMA;

    /**
     * @rdbPhysicalName RECEBE
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR 
     */
    private String RECEBE;

    /**
     * @rdbPhysicalName USUARIO
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String USUARIO;
    private Historico HistoricoReserva;

    /**
     * @label Transforma
     * @clientCardinality 1..**/
    private HOSPEDAGEM lnkHOSPEDAGEM1;
}
