/* Generated by Together */

/**
 * @persistent
 * @rdbPhysicalName RESIDENTE 
 */
public class RESIDENTE {
    public RESIDENTE() {
    }

    /**
     * @rdbPhysicalName POSTO
     * @rdbSize 30
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String POSTO;

    /**
     * @rdbPhysicalName VALOR
     * @rdbSize 8
     * @rdbLogicalType TINYINT 
     */
    private byte VALOR;

    /**
     * @rdbPhysicalName POSTO1
     * @rdbSize 30
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String POSTO1;

    /**
     * @rdbPhysicalName VALOR1
     * @rdbSize 8
     * @rdbLogicalType TINYINT 
     */
    private byte VALOR1;
}
