/* Generated by Together */

/**
 * @persistent
 * @rdbPhysicalName TABELA_DECEA
 * @rdbPhysicalPrimaryKeyName TABELADECEA_ID_PK 
 */
public class TABELA_DECEA {
    public TABELA_DECEA() {
    }

    /**
     * @rdbPhysicalName LOCALIDADE
     * @rdbNotNull
     * @rdbSize 20
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     * @rdbPrimaryKey 
     */
    private String LOCALIDADE;

    /**
     * @rdbPhysicalName LOCALIDADE1
     * @rdbNotNull
     * @rdbSize 20
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String LOCALIDADE1;
}
