/* Generated by Together */

public class TABELA_CURSOS {
    /**
     * @rdbPhysicalName <{CURSO}>
     * @rdbNotNull
     * @rdbSize 10
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     * @rdbPrimaryKey 
     */
    private String CURSO;
}
