/* Generated by Together */

public class TABELA_PRECO {
    /**
     * @rdbPhysicalName PREDIO
     * @rdbNotNull
     * @rdbSize 1
     * @rdbDigits 0
     * @rdbLogicalType CHAR
     * @rdbPrimaryKey 
     */
    private String PREDIO;

    /**
     * @rdbPhysicalName CODIGO
     * @rdbNotNull
     * @rdbSize 2
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR
     * @rdbPrimaryKey 
     */
    private String CODIGO;

    /**
     * @rdbPhysicalName POSTO
     * @rdbSize 30
     * @rdbDigits 0
     * @rdbLogicalType VARCHAR 
     */
    private String POSTO;

    /**
     * @rdbPhysicalName VALOR
     * @rdbSize 8
     * @rdbLogicalType TINYINT 
     */
    private byte VALOR;
}
