//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by VSDEPT2.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDD_VSDEPT2_FORM                101
#define IDC_DATABASE                    1006
#define IDC_CONNECT                     1007
#define IDC_DBCONNECT                   1008
#define IDC_DNAME                       1009
#define IDC_DEPTNO                      1010
#define IDC_DLOC                        1011
#define IDC_ENAME                       1012
#define IDC_EMGR                        1013
#define IDC_ESAL                        1014
#define IDC_EHIREDATE                   1015
#define IDC_MFIRST                      1016
#define IDC_MPREV                       1017
#define IDC_MNEXT                       1018
#define IDC_MLAST                       1019
#define IDC_BOOKMARK                    1020
#define IDC_TOMARK                      1021
#define IDC_BONUS                       1022
#define IDC_FIELDS                      1023
#define IDC_SESSIONS                    1024
#define IDC_TESTSEQ                     1025
#define IDC_COPYSEQ                     1026
#define IDC_DROPSEQ                     1027
#define IDC_SETSAL                      1030
#define IDC_DELETE                      1031
#define IDC_ADDNEW                      1032
#define IDC_COMMIT                      1033
#define IDC_ROLLBACK                    1034
#define IDC_STATICBOUND                 1035
#define IDC_CHECKBOX1                   1036
#define IDC_CHECKBOX2                   1037
#define IDC_RADIO1                      1038
#define IDC_RADIO2                      1039
#define IDC_RADIO3                      1040
#define IDC_RADIO4                      1041
#define IDC_HRADIO1                     1042
#define IDC_HRADIO2                     1043
#define IDC_HRADIO3                     1044
#define IDC_HRADIO4                     1045
#define IDC_HRADIO5                     1046
#define IDC_SCROLLBARW                  1047
#define IDC_SSTATICW                    1048
#define IDC_SSTATICR                    1050
#define IDC_SCROLLBARR                  1051

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1052
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
