//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by EMPEDT.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDD_EMPEDT_FORM                 101
#define IDD_LOGIND                      102
#define IDC_USERNAME                    1000
#define IDC_ENAME                       1000
#define IDC_PASSWORD                    1001
#define IDC_EMPNO                       1001
#define IDC_DATABASE                    1002
#define IDC_JOB                         1002
#define IDC_MANAGER                     1003
#define IDC_SAL                         1004
#define IDC_COMM                        1005
#define IDC_HIREDATE                    1006
#define IDC_DEPTNO                      1007
#define IDC_FIRST                       1008
#define IDC_PREV                        1009
#define IDC_NEXT                        1010
#define IDC_LAST                        1011
#define IDC_ADDNEW                      1012
#define IDC_DUPLICATE                   1013
#define IDC_DELETE                      1014
#define IDC_CONNECT                     1015

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1016
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
