CREATE TABLE "APARTAMENTO"
(
"PREDIO" CHAR NOT NULL,
"APTO" NUMBER NOT NULL,
"RAMAL" VARCHAR2,
"TV1" VARCHAR2,
"TV2" VARCHAR2,
  CONSTRAINT "APARTAMENTO_ID_PK" PRIMARY KEY ("PREDIO", "APTO")
)


CREATE TABLE "APTOCAMA"
(
"PREDIO" CHAR NOT NULL,
"APTO" NUMBER NOT NULL,
"CAMA" NUMBER NOT NULL,
"APTCODIGO" VARCHAR2,
"NOME" VARCHAR2,
  CONSTRAINT "APTOCAMA_ID_PK" PRIMARY KEY ("PREDIO", "APTO", "CAMA")
)


CREATE TABLE "ESTATISTICA"
(
"CODIGO" NUMBER,
"SITUACAO" VARCHAR2,
"VALOR" NUMBER
)


CREATE TABLE "FACILIDADE"
(
"TIPO" VARCHAR2,
"NOME" VARCHAR2,
"TELEFONE" VARCHAR2,
"ENDERECO" VARCHAR2,
"HORARIO" VARCHAR2,
"OBS" VARCHAR2
)


CREATE TABLE "HISTORICO"
(
"IDENTIDADE" CHAR NOT NULL,
"FICHA" VARCHAR2 NOT NULL,
"ANO" NUMBER NOT NULL,
"PREDIO" CHAR,
"APTO" NUMBER,
"DATAENTRADA" VARCHAR2,
"HORAENTRADA" VARCHAR2,
"DATASAIDA" VARCHAR2,
"DATAPAGAMENTO" VARCHAR2,
"NRECIBO" VARCHAR2,
"BANCO" VARCHAR2,
"NCHEQUE" VARCHAR2,
"PRACA" VARCHAR2,
"VALORPAGO" NUMBER,
"CUSTO_TELEFONE" NUMBER,
"USUARIO_ENTRADA" VARCHAR2,
"USUARIO_SAIDA" VARCHAR2,
"TIPO_FECHAMENTO" CHAR,
"RECEBIDO" CHAR,
"OBS" VARCHAR2,
"SITUACAO_CURSO" VARCHAR2,
  CONSTRAINT "HISTORICO_ID_PK" PRIMARY KEY ("IDENTIDADE", "FICHA", "ANO")
)


CREATE TABLE "HOSPEDAGEM"
(
"IDENTIDADE" CHAR NOT NULL,
"FICHA" CHAR NOT NULL,
"ANO" NUMBER NOT NULL,
"PREDIO" CHAR,
"APTO" NUMBER,
"CAMA" NUMBER,
"DATAENTRADA" VARCHAR2,
"HORAENTRADA" VARCHAR2,
"DATASAIDA" VARCHAR2,
"DEPENDENTE" NUMBER,
"SITUACAO_HOSPEDAGEM" VARCHAR2,
"RECEBE" CHAR,
"DESCONTO" CHAR,
  CONSTRAINT "HOSPEDAGEM_ID_PK" PRIMARY KEY ("IDENTIDADE", "FICHA", "ANO")
)


CREATE TABLE "HOSPEDE"
(
"IDENTIDADE" CHAR NOT NULL,
"NOME" VARCHAR2,
"NOME_GUERRA" VARCHAR2,
"POSTO" VARCHAR2,
"NACIONALIDADE" VARCHAR2,
"TELEFONE_RESIDENCIAL" VARCHAR2,
"TELEFONE_FUNCIONAL" VARCHAR2,
"SITUACAO_CURSO" VARCHAR2,
"RESIDENCIA" VARCHAR2,
"NUMERO" VARCHAR2,
"CIDADE" VARCHAR2,
"BAIRRO" VARCHAR2,
"ESTADO" VARCHAR2,
"OM_ORIGEM" VARCHAR2,
"DEPENDENTE_DE" VARCHAR2,
  CONSTRAINT "HOSPEDE_ID_PK" PRIMARY KEY ("IDENTIDADE")
)


CREATE TABLE "HOTEL_LOGS"
(
"USUARIO" VARCHAR2,
"NATIVIDADE" NUMBER,
"ATIVIDADE" VARCHAR2,
"DATA" DATE,
"HORAENTRADA" VARCHAR2
)


CREATE TABLE "HOTEL_USUARIO"
(
"USUARIO" VARCHAR2 NOT NULL,
"SENHA" VARCHAR2 NOT NULL,
"PRIVILEGIO" CHAR,
  CONSTRAINT "HOTEL_USUARIO_ID_PK" PRIMARY KEY ("USUARIO", "SENHA")
)


CREATE TABLE "LOG"
(
"STATUS" NUMBER
)


CREATE TABLE "MAPA"
(
"CODIGO" VARCHAR2,
"PREDIO" CHAR,
"APTO" NUMBER,
"CAMA" NUMBER,
"RAMAL" CHAR,
"TV1" CHAR,
"TV2" CHAR,
"TIPO" CHAR,
"SITUACAO" VARCHAR2,
"SITUACAO_CURSO" VARCHAR2,
"NOME" VARCHAR2,
"DATA_ENTRADA" VARCHAR2,
"DATA_SAIDA" VARCHAR2
)


CREATE TABLE "RESERVA"
(
"IDENTIDADE" CHAR,
"DATAENTRADA" DATE,
"NOME" VARCHAR2,
"NOME_GUERRA" VARCHAR2,
"POSTO" VARCHAR2,
"DEPENDENTE_DE" VARCHAR2,
"TELEFONE_FUNCIONAL" VARCHAR2,
"SITUACAO_CURSO" VARCHAR2,
"OM_ORIGEM" VARCHAR2,
"DEPENDENTE" NUMBER,
"HORAENTRADA" VARCHAR2,
"DATASAIDA" DATE,
"PREDIO" CHAR,
"APTO" NUMBER,
"CAMA" NUMBER,
"RECEBE" CHAR,
"USUARIO" VARCHAR2
)


CREATE TABLE "RESIDENTE"
(
"POSTO" VARCHAR2,
"VALOR" NUMBER
)


CREATE TABLE "RESPONSAVEL"
(
"CODIGO" NUMBER NOT NULL,
"FUNCAO" VARCHAR2,
"NOME" VARCHAR2,
  CONSTRAINT "RESPONSAVEL_ID_PK" PRIMARY KEY ("CODIGO")
)


CREATE TABLE "TABELA_CURSOS"
(
"CURSO" VARCHAR2 NOT NULL,
  CONSTRAINT "TABELACURSOS_ID_PK" PRIMARY KEY ("CURSO")
)


CREATE TABLE "TABELA_DECEA"
(
"LOCALIDADE" VARCHAR2 NOT NULL,
  CONSTRAINT "TABELADECEA_ID_PK" PRIMARY KEY ("LOCALIDADE")
)


CREATE TABLE "TABELA_POSTO"
(
"CODIGO" VARCHAR2 NOT NULL,
"CODTABELA" VARCHAR2 NOT NULL,
"POSTO" VARCHAR2,
  CONSTRAINT "TABELAPOSTO_ID_PK" PRIMARY KEY ("CODIGO", "CODTABELA")
)


CREATE TABLE "TABELA_PRECO"
(
"PREDIO" CHAR NOT NULL,
"CODIGO" VARCHAR2 NOT NULL,
"POSTO" VARCHAR2,
"VALOR" NUMBER,
  CONSTRAINT "TABELAPRECO_ID_PK" PRIMARY KEY ("PREDIO", "CODIGO")
)


CREATE TABLE "VERIFICA"
(
"VUSUARIO" VARCHAR2,
"VDATA" DATE,
"VHORAENTRADA" VARCHAR2,
"VHORASAIDA" VARCHAR2
)


