   ALTER TABLE Historico ADD CONSTRAINT Historico_fk FOREIGN KEY (Identidade) References Hospede(Identidade) on delete Cascade;
   ALTER TABLE Apartamento ADD CONSTRAINT Apartamento_Id_pk PRIMARY KEY (Predio,Apto);
   ALTER TABLE AptoCama ADD CONSTRAINT AptoCama_Id_pk PRIMARY KEY (Predio,Apto,Cama);
   ALTER TABLE AptoCama ADD CONSTRAINT Apto_AptoCama_fk FOREIGN KEY (Predio, Apto) References Apartamento (Predio, Apto) on delete Cascade;
   ALTER TABLE Dependente ADD CONSTRAINT Dependente_Id_pk PRIMARY KEY (Ficha, Ano, Predio, Apto, Cama);
   ALTER TABLE Dependente ADD CONSTRAINT Dependente_fk FOREIGN KEY (Identidade, Ficha, ano) References hospedagem (Identidade, Ficha, ano) on delete Cascade;
   ALTER TABLE Estatistica ADD CONSTRAINT Estatistica_pk PRIMARY KEY (Codigo);
   ALTER TABLE Historico ADD CONSTRAINT Historico_Id_pk PRIMARY KEY (Identidade, Ficha, ano);
   ALTER TABLE Hospedagem ADD CONSTRAINT Hospedagem_Id_pk PRIMARY KEY (Identidade, Ficha, Ano);
   ALTER TABLE Hospedagem ADD CONSTRAINT Hospedagem_fk FOREIGN KEY (Identidade) References Hospede(Identidade) on delete Cascade;
   ALTER TABLE Hospedagem ADD CONSTRAINT Hospedagem_AptoCama_fk FOREIGN KEY (Predio, Apto, Cama) References AptoCama (Predio, Apto, Cama) on delete Cascade;
   ALTER TABLE Hospede ADD CONSTRAINT Hospede_Id_pk PRIMARY KEY (Identidade);
   ALTER TABLE Hotel_Usuario ADD CONSTRAINT Hotel_Usuario_Id_pk PRIMARY KEY (Usuario, Senha);
   ALTER TABLE Reserva ADD CONSTRAINT Reserva_fk FOREIGN KEY (Predio, Apto, Cama) References AptoCama(Predio, Apto, Cama) on delete Cascade;
   ALTER TABLE Responsavel ADD CONSTRAINT Responsavel_Id_pk PRIMARY KEY (Codigo);
   ALTER TABLE Tabela_Cursos ADD CONSTRAINT TabelaCursos_Id_pk PRIMARY KEY (Curso);
   ALTER TABLE Tabela_Decea ADD CONSTRAINT TabelaDecea_Id_pk PRIMARY KEY (Localidade);
   ALTER TABLE Tabela_Posto ADD CONSTRAINT TabelaPosto_Id_pk PRIMARY KEY (Codigo, CodTabela);
   ALTER TABLE Tabela_Preco ADD CONSTRAINT TabelaPreco_Id_pk PRIMARY KEY (Predio, Codigo);
   ALTER TABLE Verifica ADD CONSTRAINT Verifica_pk PRIMARY KEY (VUsuario, VData, VHoraEntrada);
   select CONSTRAINT_NAME from user_constraints;